# Generated by Django 6.0.6 on 2026-06-25 09:43

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('category', models.CharField(choices=[('Smartphones', 'Smartphones'), ('Chargers', 'Chargers'), ('Back Covers', 'Back Covers')], max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'indexes': [models.Index(fields=['category'], name='product_category_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='product_tags_idx')],
            },
        ),
    ]
